# Generated by Django 5.0.2 on 2024-05-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_customuser_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersubject',
            old_name='darasa',
            new_name='classes',
        ),
    ]
