# Generated by Django 5.0.2 on 2024-05-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_darasa_teachersubject_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='classes',
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='classes_Stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.classstream'),
            preserve_default=False,
        ),
    ]
